apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-valheim-saves-pv-claim
  namespace: valheim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
