apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-saves-pv-claim
  namespace: valheim
spec:
  storageClassName: "valheim"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
