apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "valheim-disk"
  namespace: "openshift-local-storage" 
spec:
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd4-valheim-7j4vx
  storageClassDevices:
    - storageClassName: "valheim" 
      volumeMode: Filesystem 
      fsType: xfs 
      devicePaths: 
        - /dev/sdb
