apiVersion: v1
kind: PersistentVolume
metadata:
  name: valheim-game-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare/valheim/game
    server: 192.168.1.242 
