apiVersion: v1
kind: PersistentVolume
metadata:
  name: valheim-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare/valheim-backups
    server: 192.168.1.242 
